//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Server.MyMicroservice.MyMicroservice"/> </summary
    public sealed class MyMicroserviceClient : Beamable.Server.MicroserviceClient
    {
        
        /// <summary>
        /// Call the AddMyValues method on the MyMicroservice microservice
        /// <see cref="Beamable.Server.MyMicroservice.MyMicroservice.AddMyValues"/>
        /// </summary>
        public Beamable.Common.Promise<int> AddMyValues(int a, int b)
        {
            string serialized_a = this.SerializeArgument<int>(a);
            string serialized_b = this.SerializeArgument<int>(b);
            string[] serializedFields = new string[] {
                    serialized_a,
                    serialized_b};
            return this.Request<int>("MyMicroservice", "AddMyValues", serializedFields);
        }
    }
}
